
services:
  backend:
    build: ./FastAPI
    ports:
      - "8000:8000"
    volumes:
      - ./FastAPI:/app
    depends_on:
      - frontend

  frontend:
    build: ./React/userhub
    ports:
      - "3000:3000"
    volumes:
      - ./React/userhub:/app
